export const data = [{
        "title": "Kingsglaive",
        "desc": "King Regis, who oversees the land of Lucis, commands his army of soldiers to protect the kingdom from the Niflheim empire's plans to steal the sacred crystal.",
        "URLimage": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSxTjN1-UnV53Lbn-X82ECdoWPVN-9l_4d7a-tN8BHJTFXL22m6",
        "rating": 6,
        "trailer": "https://www.youtube.com/embed/htnkOpknGok",
        "date": 2022,
        "duration": "1h45min",
    },
    {
        "title": "Final Fantasy",
        "desc": "A scientist makes a last stand on Earth with the help of a ragtag team of soldiers against an invasion of alien phantoms.",
        "URLimage": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRUL9vi5vfTxOkaZGks-1TxdCmkD7oFli3TBXBOzkjG4fXwRBUd",
        "rating": 10,
        "trailer": "https://www.youtube.com/embed/4tyuIh12_HU",
        "date": 2019,
        "duration": "2h19min",
    },
    {
        "title": "Ghost In The Shell",
        "desc": "A hacker known as the Puppet Master is hunted by a female cyborg cop and her partner. This film is a revised version of Ghost in the Shell (1995).",
        "URLimage": "https://m.media-amazon.com/images/I/71dFSa9X39L._SY445_.jpg",
        "rating": 5,
        "trailer": "https://www.youtube.com/embed/G4VmJcZR0Yg",
        "date": 2020,
        "duration": "1h44min",
    },
    {
        "title": "Appleseed Alpha",
        "desc": "A young female soldier Deunan and her cyborg partner Briareos survive through the post World War 3 apocalyptic New York in search of human's future hope.",
        "URLimage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-g1vdZ5IqsxgJRWSi_j3ZlM5Wuy2EemjCuEAtTN45TsSexdnj",
        "rating": 8,
        "trailer": "https://www.youtube.com/embed/4DtWCjogd1M",
        "date": 2018,
        "duration": "1h30min",
    },
    {
        "title": "Resident Evil",
        "desc": "Chris Redfield enlists the help of Leon S. Kennedy and Rebecca Chambers to stop a death merchant, with a vengeance, from spreading a deadly virus in New York.",
        "URLimage": "https://movieposters2.com/images/701843-b.jpg",
        "rating": 7,
        "trailer": "https://www.youtube.com/embed/W1OUs3HwIuo",
        "date": 2015,
        "duration": "1h22min",
    }
];